### ISSUE TITLE
Installation directory

### ISSUE THREAD

**Issue by Daedalon** [orizens/sublime-angular2-snippets#2]
The instructions currently state only "download a zip or clone this repo to your sublime's User directory." A quick search did not reveal the correct directory. Tried saving the repository as a zip to 
`C:\Users\[username]\AppData\Roaming\Sublime Text 3` and restarting Sublime, but it didn't have any effect.

What's the correct directory?

**Comment by orizens** [comment]
hi @Daedalon 
please unzip the contents to your sublime "User" directory.
